controller_manager:
  ros__parameters:

    update_rate: 100 # Hz

#    joint_state_broadcaster:
#      type: joint_state_broadcaster/JointStateBroadcaster
#
#    io_and_status_controller:
#      type: ur_controllers/GPIOController
#
#    speed_scaling_state_broadcaster:
#      type: ur_controllers/SpeedScalingStateBroadcaster
#
#    force_torque_sensor_broadcaster:
#      type: ur_controllers/ForceTorqueStateBroadcaster
#
#    joint_trajectory_controller:
#      type: joint_trajectory_controller/JointTrajectoryController
#
#    scaled_joint_trajectory_controller:
#      type: ur_controllers/ScaledJointTrajectoryController
#
#    forward_velocity_controller:
#      type: velocity_controllers/JointGroupVelocityController
#
#    forward_position_controller:
#      type: position_controllers/JointGroupPositionController
